- .github/workflows/npm-test.yml
This adds a GitHub Actions workflow to run `npm test` and `npm run lint` against PR's. They will show up as separate checks in the PR checks list.
Behavior can be observed on this PR (GitHub Actions use the configuration from the PR itself when running against a PR).
Based on discussion with @jacekkolasa on Slack.
> Run tests and linter against PR's.

- .github/workflows/release.yml
When a new release is created, this will automatically build the dashboard and add a rlease asset containing a compressed tarball of the build directory.
Long-term, this can be easily expanded to publish to NPM (if we choose to do so) and open a PR against https://github.com/netdata/netdata to update the packaging code there to use the newly released version of the dashboard.
Closes: #26
> Add basic release build automation.

- .github/workflows/release.yml
This will ensure it only runs once on relase creation, so that we don't have failures do to multiple upload attempts.
> Fix syntax issue in release workflow.

- package-lock.json
- package.json
- src/domains/chart/components/disable-out-of-view.tsx
- src/domains/chart/components/lib-charts/__tests__/dygraph-chart.test.tsx
- src/domains/chart/components/lib-charts/dygraph-chart.tsx
- src/hooks/use-show-value-outside.ts
- src/index-npm.ts
- some performance fixes, regarding scrolling in Dashboard/Node-View. Generally i've put more effort to not update dygraph instance too often after mount. Unfortunately it's at the cost of putting more stuff into refs :/
- exposed global-pan-and-zoom action, to be used by Node View (we'll talk about it)
- small bugfix in data-show-value-outside hook
> 8363-perf-fixes

- package-lock.json
- package.json
- src/domains/chart/sagas.ts
breaking change - if it's not main.js (ie. is Cloud), expect full url in `host` (ending with /api/v1/nodes/{nodeID}/data)
> aclk-host-fix

- package-lock.json
- package.json
- src/domains/chart/sagas.ts
- src/domains/chart/utils/get-chart-pixels-per-point.ts
- src/utils/api.ts
- src/utils/netdata-sdk/metrics-stream.ts
set timeout for metrics-data calls, to 15s
attributes.pointsPerPixes is now overwriting existing settings even if it's lower (previously it was Math.max() with settings/defaults)
allowed more simultaneus calls (60 for cloud)
> fix-cloud-timeouts

- package-lock.json
- package.json
- src/App.tsx
- src/utils/server-detection.ts
@VLegakis i disabled the notifications for now, i know that your PR contains the fix, but i don't have time for testing this, let's just not have notifications and /api/v1/info polling at all next stable release (after weekend)
> remove notifications and fix /default.html route

- package-lock.json
- package.json
- src/domains/chart/components/abstract-chart.tsx
- src/domains/chart/components/lib-charts/sparkline-chart.tsx
- src/domains/chart/utils/transformDataAttributes.ts
new forceTimeWindow attribute, with support in sparkline-chart. It displays time-range as requested, even when there are no available data
I decided just to make the chart smaller in this case and shift it via padding-left. First i was trying to do it on library-level, but the only option was to add nulls (empty points). Given much higher resolution (instead of 30 days user could get 2 hours, still spreading across hundreds points) the array was too big and it was not performant.
> sparkline - force time window

- package-lock.json
- package.json
- src/domains/chart/components/lib-charts/sparkline-chart.tsx
don't do unnecessary corrections when requested window is only a little different from available one
> force time window - prevent negative padding

- package-lock.json
- package.json
- src/domains/chart/actions.ts
- src/domains/chart/components/chart-with-loader.tsx
- src/domains/chart/sagas.ts
- src/hooks/use-common-intersection.ts
- src/utils/netdata-sdk/metrics-stream.ts
- fix race condition in intersection observer. UseEffect was firing later than intersection observer making sequential callback, which caused unsync
- remove profile flag from build task (that looks scary, but it had minor impact on performance when i tested it)
- cancel request when chart goes out of view
> netdata-1-21-fix

- package.json
- src/components/app-header/components/version-control/version-control.tsx
- src/index-npm.ts
The dashboard uses already a Version Control component making all the necessary calls and handling which I expose with this PR since we can easily reuse on the cloud for the required UI 
https://www.figma.com/file/OyGGjJd0Dm7GnscRvSP3Fk/%E2%9C%85S3.3---Node-View?node-id=0%3A1
https://github.com/netdata/product/issues/693
Overall they will look exactly the same as in the agent Nav bars. So better avoid any duplicate code and handling by exposing this component and reusing it in the cloud.
> Expose version control component

- src/domains/chart/components/abstract-chart.tsx
- src/domains/chart/components/chart.tsx
- src/domains/chart/components/disable-out-of-view.tsx
- src/domains/chart/components/lib-charts/dygraph-chart.tsx
- src/domains/chart/utils/formatters.ts
- src/hooks/use-common-intersection.ts
This is an fix-extension. I'm putting it in separate PR, because it's a bigger change and until we decide to fix the stable release, it's good to have both versions available.
This will go as v0.4.14 to `netdata`
Change the way we freeze elements. Clone it (so it's decoupled from React), but don't store the clone in state (to prevent updates), instead keep in ref for instant access. Update the clone's visibility based on Intersection Observer, changing the visibility immediately when it's in the scope. But note - the chart is starting to render after some async timeout (shouldHideDebounced property)
> netdata-1-21-fix-extended

- src/domains/global/sagas.ts
8581: fix for encoded chars in urls: don't encode url and name for private registry (axios already does that, which resulted in wrong double encoding)
fixes https://github.com/netdata/netdata/issues/8581
> 8581-special-chars-private-registry

- package-lock.json
- package.json
- src/domains/chart/components/chart-with-loader.tsx
- src/domains/chart/components/lib-charts/dygraph-chart.tsx
- src/domains/chart/selectors.ts
- src/domains/global/options.ts
- src/index-npm.ts
fixes:
- after sidebar toggle, resize dygraph (separate condition, because dygraph auto-resize on window width change, but don't detect other changes)
- prevent making new calls when previous for the chart are already in progress
> dygraph resize and api throttling

- src/components/app-header/app-header.tsx
- src/main.js
- fix situation where when loading snapshot easypiechart was resulting in error
- better iframe-load-error detection for firefox (fixes unwanted lack of sign-in button)
> snapshot-fix

- src/App.tsx
- src/components/app-header/app-header.tsx
- src/components/app-header/styled.ts
- src/domains/chart/components/lib-charts/dygraph-chart.tsx
- src/utils/post-message.ts
- fix navbar icons (unnecessary paddings, a result of race condition between bootstrap.css and styled-components)
- safer time when resizing dygraph after toggling sidebar (additional RAF)
- leave door open for logout dropdown (allow setting width/height from iframe, which need more space sometimes, when dropdown is opened)
> misc-fixes

- public/dashboard.js
- src/utils/units-conversion.ts
fixes https://github.com/netdata/dashboard/issues/88
We need that last units-conversion fix in the new Netdata release, but the dashboard is too far ahead, so i created a branch off last commit from https://github.com/netdata/dashboard/releases/tag/v1.0.14 and added the bytes-conversion change. Other changes are not tested enough to go to that release
> bytes-conversion

- package-lock.json
- package.json
- src/domains/chart/components/chart-container/chart-container.tsx
- src/domains/chart/components/chart-dropdown/chart-dropdown.tsx
- src/domains/chart/components/chart-with-loader/chart-with-loader.tsx
- src/domains/chart/sagas.ts
- src/index-npm.ts
- pass attributes and metadata to dropdown callback (needed by custom-dashboards)
- support fetching metadata from ACLK directly by charts
- add few more exports (types) so we can import them from single index-npm.ts file
> few tweaks needed by custom dashboards

- src/main.js
The same fixes as found in netdata/#9394, but for the new dashboard.
> Fix links to documentation and text for database engine in new dashboard menu

- dashboard-react.js
- package-lock.json
- package.json
- src/domains/chart/components/lib-charts/dygraph-chart.tsx
- src/domains/chart/components/lib-charts/dygraph/utils.ts
- src/types/global.ts
fixes https://github.com/netdata/netdata/issues/9663
Stacked charts with negative values were not supported by dygraph.js, so i've built a hack around how dygraph.js works - for such charts, whenever negative value appears in stacked chart, FE now sums the values manually
> fake-stacked chart type

- src/main.js
when clicking on alarm log, scroll and center in time directly, don't go through cloud/registry (we don't mix alarms from different nodes yet)
fixes https://github.com/netdata/netdata/issues/6975
> alarm log click centering

- src/domains/chart/components/lib-charts/dygraph-chart.tsx
- src/vendor/dygraph-c91c859.min.js
change dygraph version to the same which was used in old dashboard. That version had a fix from @ktsaou for constant other than 0. In those cases no y-legend was present and autoscaling was broken.
Instead of uploading full js file to the repo, i linked already existing file in /public, which normally is used for hosting old dashboard in the Agent. I checked that `npm run build` works fine and fixes similar problem when added to cloud-fe.
related issue: https://github.com/netdata/netdata/issues/9659
old issue explaining the problem: https://github.com/netdata/netdata/pull/3407
> y-axis and scaling for constant values fix

- package-lock.json
- package.json
- src/domains/chart/utils/formatters.ts
auto-formatting of static values (where data.min === data.max), it was sometimes broken due to bug in refactor
(additional fix for https://github.com/netdata/netdata/issues/9659)
> auto formatting static fix

- src/domains/chart/components/lib-charts/d3pie-chart.tsx
D3 pie chart was not converting units properly on data updates, here's a fix
related issue: https://github.com/netdata/netdata/issues/9386
> d3-pie chart unit conversion

- package-lock.json
- package.json
- src/domains/chart/actions.ts
- src/domains/chart/components/chart-with-loader/chart-with-loader.tsx
- src/domains/chart/components/chart.tsx
- src/domains/chart/sagas.ts
- src/domains/dashboard/components/head-main.tsx
- src/domains/dashboard/components/node-view/node-view.tsx
- src/domains/dashboard/components/node-view/render-submenu-name.tsx
- src/utils/fill-missing-data.test.ts
- src/utils/fill-missing-data.ts
When requesting for bigger time interval than available history in the agent, we get only the available range. Dashboard was first designed to not allow zooming-out too much, so when we were requesting too big range, we were getting in response the same nr of points requested, but in smaller time frame (for available history). We want to force the requested time frame, so that bigger frequency is a waste, and instead we'll now request reduced nr of points, and after getting response, we'll fill empty data, so that charts have requested time-frame on x-axes.
> fill fake nulls when requesting more than available history

- copy-assets.js
- package-lock.json
- package.json
- src/domains/chart/components/chart-with-loader/chart-with-loader.tsx
Fixed inconsistency in nodes length between rerenders.
Fyi: As discussed with @jacekkolasa we are going to keep our eye on this, to check if there are any perf issues. The next step is to expose a dashboard selector that we can use from the parent component (in this case cloud) (Thanks @jacekkolasa )
> Remove ref from chart data

- package-lock.json
- package.json
- src/domains/chart/components/chart-legend-bottom.styled.ts
- src/domains/chart/components/chart-spinner/chart-spinner.tsx
- src/domains/chart/components/chart-spinner/styled.ts
- src/domains/chart/components/lib-charts/dygraph-chart.tsx
- src/domains/dashboard/components/node-view/node-view.scss
- src/domains/dashboard/components/node-view/render-submenu-name.tsx
- src/domains/dashboard/utils/netdata-dashboard.ts
- src/styles/dashboard.css
- src/styles/dashboard.slate.css
- new animated svg spinner
- clean z-indexes to fix cloud-dropdowns problems
- align node-view headers to the left
- add more horizontal space between node-view sections
- dygraph tweaks when legend is on the bottom - remove redundant units, smaller y-axis legend, align to left
- remove unnecessary effects when selecting bottom-legend dimensions
> styling fixes

- package-lock.json
- package.json
- src/domains/chart/sagas.ts
Remove context and other composite-charts related params. When we'll release composite-charts, that will be replaced with separate POST call which is already in develop/staging
The 2.0.1-context-hotfix branch has been created from last commit in Dashboard which is currently in cloud's production
> context production hotfix

- package-lock.json
- package.json
- src/domains/chart/components/chart-legend-bottom.styled.ts
- src/domains/chart/components/chart-spinner/chart-spinner.tsx
- src/domains/chart/components/chart-spinner/styled.ts
- src/domains/chart/components/chart-with-loader/chart-with-loader.tsx
- src/domains/dashboard/components/node-view/node-view.scss
- indent dygraph-title to the left, when legend is on the bottom
- bigger spinner for gauge/pie charts, even bigger for dygraphs
- expose spinner to show-spinner-always localstorage property (for debugging reasons)
- add max-height and auto-scrollbar, in case there are too many rows of legend-on-the-bottom
> legend-and-spinner-improvements

- src/domains/dashboard/components/head-main.tsx
So there is an issue regarding the Guages: 
We want them not getting affected by aggregation methods and dimensions coming in from the cloud (So if someone plays around with the relevant chart's definition the top Gauges are not affected)
In this spirit I sent the last PR ignoring the attribute overrides coming from the cloud specifically for these charts as we agreed with @jacekkolasa .
BUT this means the aggrMethod param will always be added in the gauge Charts data calls. 
Meaning even for Agent Dashboard.
It doesn't cause any issue for the moment since agents just ignore this param. 
However I think we should find some better solution.
For the moment I add anywhere it was missing the aggMethods and relevant units TBD
> Update aggrMethods and units

- src/main.js
Simple update of the link to the changelog when an update is available. Refer to https://github.com/netdata/netdata/pull/10024.
> Fix broken changelog link

- src/domains/chart/sagas.ts
- src/domains/dashboard/components/node-view/node-view.tsx
- src/domains/dashboard/components/node-view/render-submenu-name.tsx
fix heads and mainheads to use default aggrMethod (separate from selected option for dygraphs in the cloud)
fix GET calls instead of composite-chart POST for heads
> composite-charts-heads-fix

- src/App.tsx
- src/components/app-header/styled.ts
- src/components/space-panel/styled.ts
- src/components/spaces-bar/styled.tsx
- src/components/time-group/styled.ts
- src/domains/dashboard/components/sidebar-social-media/sidebar-social-media.tsx
- src/domains/dashboard/components/sidebar-social-media/styled.ts
- src/domains/global/options.ts
- src/styles/main.css
- src/utils/map-theme.ts
- make header colors constant, because it's not yet ready for changing theme
- sign-in buttons hover fixes
- propagate Dashboard's theme from localStorage to styled-components
- social media links styling (fixed white theme, correct typo)
- hide small white dot, left from old iframe
- add more space on top so first header is visible below the new time-frame bar
> dashboard styling fixes

- package-lock.json
- package.json
- src/domains/dashboard/components/node-view/render-submenu-name.tsx
related issue: https://github.com/netdata/netdata/issues/10118
Use dangerouslySetInnerHTML to display submenu info written in HTML in dashboard_info.js, just like we do it for other parts in node-view.
> submenu-info html fix

- src/domains/chart/components/lib-charts/dygraph-chart.tsx
- src/domains/chart/components/lib-charts/proceeded-chart-disclaimer.test.tsx
- src/domains/chart/components/lib-charts/proceeded-chart-disclaimer.tsx
- src/domains/chart/hooks/use-proceeded-chart.ts
This Pull Request closes issue https://github.com/netdata/netdata/issues/8952
- Created the disclaimer component
- Created the proceeded identification functionality
- Added the component to the charts
The identification logic was copied from the old implementation
> Proceeded chart disclaimer

- src/domains/chart/actions.ts
- src/domains/chart/components/chart-with-loader/chart-with-loader.tsx
- src/domains/chart/components/lib-charts/dygraph-chart.tsx
- src/domains/chart/components/lib-charts/dygraph/utils.ts
- src/domains/chart/sagas.ts
- src/domains/chart/utils/get-chart-url-options.ts
- src/domains/chart/utils/transformDataAttributes.ts
- Adds the double aggregation logic that is required if the group is by node.
- Change chart type if it is required by the business logic
> Group by node

- package-lock.json
- package.json
- src/domains/chart/components/lib-charts/dygraph-chart.tsx
Resize the chart when the names in the legend are getting changed. So we avoid the issue in the following schreenshot.
> Resized the chart when dimensions change.

- src/components/app-header/app-header.tsx
- src/domains/chart/actions.ts
- src/domains/chart/reducer.ts
- src/main.js
https://github.com/netdata/netdata/issues/10263
Fixes a problem when exporting a snapshot for a second time in given session only exports single chart.
> 10263 export snapshot fix

- src/components/app-header/components/panel-control/panel-control.tsx
- src/components/space-panel/space-panel.tsx
- src/utils/utils.ts
When user manually closes the sidebar, persist it (in localStorage).
Side note - I didn't implemented persisting opened state for now, because that needs fixing the "pending" state where we see invitation-to-cloud in space-panel before sso iframes call back
> persist closed sidebar

- package.json
- src/custom-dashboards-app.tsx
- fix start:tv task
- add themeProvider to custom-dashboards-app, since it's needed by charts
> custom-dashboards-app workflow fix

- src/domains/chart/components/chart.tsx
- src/domains/chart/components/disable-out-of-view.tsx
- src/domains/global/actions.ts
- src/domains/global/reducer.ts
- allow resetting relative zoom when current setting is already relative - when "play" button is pressed and the mode is "relative" (last x minutes etc.), then the timeframe is reset to the initial value
- allow testing "aggresive chart state cleaning" impact on performance - if `wipe-chart-state` property in localStorage is truthy, then when chart scroll out of view it destroys the state
> reset relative zoom

- package-lock.json
- package.json
- src/styles/dashboard.css
- src/styles/dashboard.slate.css
- src/theme-provider.tsx
https://github.com/netdata/cloud-frontend/issues/2426
when user has not specified theme, it was looking very bad in few places:
> "unspecified" theme fix - fallback to dark

- package-lock.json
- package.json
- src/dashboard_info.js
- src/domains/chart/actions.ts
- src/domains/chart/chart-types.ts
- src/domains/chart/components/chart-container/chart-container.tsx
- src/domains/chart/components/chart-with-loader/chart-with-loader.tsx
- src/domains/chart/components/lib-charts/dygraph/utils.ts
- src/domains/chart/sagas.ts
- src/domains/chart/utils/get-chart-url-options.ts
- src/domains/chart/utils/transformDataAttributes.ts
- src/domains/dashboard/components/chart-wrapper.tsx
- src/domains/dashboard/components/node-view/node-view.tsx
- src/domains/dashboard/components/node-view/render-submenu-name.tsx
- src/domains/dashboard/utils/is-kubernetes-chart.ts
- src/domains/dashboard/utils/render-charts-and-menu.ts
- Support requests with groupBy label.
- Render an optional view before the charts.
- Propagate an `onAttributesChange` callback.
> Kubernetes

- package-lock.json
- package.json
- src/domains/chart/chart-types.ts
- src/domains/chart/components/abstract-chart.tsx
- src/domains/chart/components/chart-with-loader/chart-with-loader.tsx
- src/domains/chart/components/chart.tsx
- src/domains/chart/components/lib-charts/__tests__/dygraph-chart.test.tsx
- src/domains/chart/components/lib-charts/dygraph-chart.tsx
- src/domains/chart/components/lib-charts/sparkline-chart.tsx
- src/domains/chart/reducer.test.ts
- src/domains/chart/reducer.ts
- src/domains/chart/selectors.ts
- src/domains/global/reducer.ts
- src/utils/utils.ts
I've changed the way we update dygraph during panning.
- we always keep "requested" timeframe instead of timeframe that we get from data - so consecutive requests don't trigger when request for "similar" timeframe is already pending
- similar to the old dashboard, when user pans we debounce the requests until user pauses for 400 ms or there's a mouse-up event
- i've added a separate dependency - "useDebouncedCallback" from "use-debounce" hook that works much better than the one from "react-use" library, because it doesn't introduce a separate state, instead it works only on callbacks
- improved few memoizations, especially `dimensions` and `colours`, preventing some unnecessary updates
> dygraph panning responsiveness

- src/domains/chart/components/chart.tsx
- src/domains/chart/components/resize-handler.tsx
- src/domains/chart/utils/get-portal-node-styles.ts
Old Dashboard was persisting heights of all charts to localStorage, even if they haven't been changed by the user. Now, if users open the dashboard with new legends, that persisted height will be set to both chart+legend, resulting in much smaller, hard-to-read charts. Unfortunately we don't know if that height was set in old dashboard, new dashboard or new dashboard with legend-on-bottom.
To minimize the "inconvenience", i've added a detection of old-dashboard properties, that will not enforce the height of old default values, ie. 180px and 90px. We omit that height in this case.
I've also changed a key for that property (with a read-fallback for old one), so that now when we persist, we save the height adjusted by current legend-position setting. In the future when we'll toggle this …
> fix chart heights for new legend

- src/domains/chart/components/lib-charts/dygraph-chart.tsx
- src/domains/chart/components/lib-charts/dygraph/utils.ts
fix problematic dygraph's feature, to limit "overlapping" of third-party iframes, which causes unwanted scrollbar on panning
> fix dygraph's iframes overlapping

- src/utils/fill-missing-data.ts
Fix situation when unsuficcient-history combined with composite-charts results with gauge charts data calls handling error.
> fix composite-charts with low-history gauge charts data handling

- package-lock.json
- package.json
- src/domains/chart/chart-types.ts
- src/domains/dashboard/utils/netdata-dashboard.ts
- src/domains/dashboard/utils/render-charts-and-menu.ts
https://github.com/netdata/netdata-cloud/issues/25
- use "cgroups" instead of buggy "group" name for cgroups section (override group title when overview is detected)
- group prometheus charts by job name
> overview grouping issues

- src/main.js
- use all pages when exporting alarms log 
- always use date+time in alarms log, so when it's exported we have all information (bootstrap-table doesn't allow changing formatting for view and export)
> alarms-log-export-fix

- public/index.html
- src/main.js
move "demo" info above charts, without so that right side with date-picker and menu stays intact and doesn't overlap
from:
to:
> fix demo - datepicker overlap

- src/components/date-picker/redux-wrapped-picker.tsx
- src/domains/dashboard/sagas.ts
- src/main.js
Persist relative timeframe (negative "after") in url.
Because that url dependes on 2 separate states (globalPanAndZoom, defaultAfter), i moved the logic out of sagas to redux-wrapped-picker, so it's working simlarly to cloud now.
> persist relative timeframe in agent

- src/domains/chart/components/chart-legend-right.tsx
- src/domains/chart/components/chart-legend.tsx
- src/domains/chart/components/chart.tsx
Unfortunately lint warnings blocked the release build
> Treating warnings as errors because process.env.CI = true.
> Most CI servers set it automatically.
> fix lint warnings to unblock release build

- package-lock.json
- package.json
- src/App.tsx
- src/domains/chart/components/disable-out-of-view.tsx
- src/domains/chart/components/lib-charts/alarmBadge.js
- src/domains/chart/components/lib-charts/dygraph-chart.tsx
- src/domains/chart/hooks/useAlarmBadge.js
- src/domains/chart/hooks/useDygraphBadge.js
- src/domains/chart/utils/get-portal-node-styles.ts
- src/domains/dashboard/hooks/useAlarmFromUrl.js
- src/domains/global/actions.ts
- src/domains/global/constants.ts
- src/domains/global/reducer.ts
- src/domains/global/selectors.ts
- src/domains/global/types.ts
- src/index-npm.ts
- src/main.js
Display a alarm overlay and a badge when dashboard is accessed with specific hash params.
Expose parts of it so cloud-fe can reuse it.
This is how it looks like, but most likely we'll be changing it in following iterations
> alarm-overlays

- package-lock.json
- package.json
- src/domains/chart/components/lib-charts/alarmBadge.js
- src/domains/chart/components/lib-charts/dygraph-chart.tsx
- src/index-npm.ts
- src/utils/hash-utils.ts
Don't split hash params by white-space, to fix problems with rich alarm values
Also added other changes that already are in cloud-frontend, and exposed them so we can avoid duplication.
> hash manipulation fix

- src/email-templates/alert-notification/footer.mjml
- src/email-templates/alert-notification/header.mjml
- src/email-templates/alert-notification/notification-template.mjml
- src/email-templates/alert-notification/output.html
We have a common alarm template in [Agent](https://github.com/netdata/netdata/blob/alerts-changes-notify-attributes/health/notifications/alarm-notify.sh.in#L2863-L3673) and in the Cloud. To have the common source of truth, let's keep it here.
It is in 2 formats:
1) .mjml files (see https://mjml.io/)
2) .html file (output.html) copy/pasted from mjml app. In the future, if we want, we can use mjml npm package to automatically generate output.html.
> Alarm template

- package-lock.json
- package.json
- src/domains/chart/components/lib-charts/alarmBadge.js
- src/domains/chart/components/lib-charts/dygraph-chart.tsx
- prevent badge wrapping when being on left side of the screen
- update highlight immediately after clearing current alarm
This is already released on *npm* as v2.15.5
> badge wrap + clear-alarm fixes

- src/main.js
We should force break "words" on values that are really long, in order to prevent layout from breaking - i.e. `alert source` can be a long path.
> Fixed word breaking on alarms modal.

- .github/workflows/release.yml
This will automatically run a workflow in the agent repo to generate a PR to update the agent to the newest version of the dashboard whenever a release that is not a prerelease is created.
This will be marked ready for review once netdata/netdata#11076 is merged, as it has a hard dependency on that PR.
Closes: #269 
I’ve tagged @netdata/cloud-fe for review to get a confirmation that the described behavior is what we want. The other review requests are to help ensure correctness of the change itself.
> Automatically trigger an agent PR on dashboard release.

- src/domains/global/sagas.ts
Add some new properties from /info to "agent dashboard" PostHog events.
Since we now have some more properties available via the /api/v1/info endpoint, it would be useful to also add them to the agent dashboard frontend pageview and autocapture events via the existing posthog.register() call.
> Add some new properties from /info to telemetry

- public/dashboard.html
- public/demo.html
- public/demo2.html
- public/demosites.html
- public/demosites2.html
- public/index-node-view.html
- public/infographic.html
- public/tv-react.html
- public/tv.html
This PR changes "NetData" to "Netdata" (according to [style-guide](https://github.com/netdata/netdata/blob/master/docs/contributing/style-guide.md#capitalization)).
> Clean netdata naming

- src/domains/dashboard/utils/render-charts-and-menu.ts
- src/main.js
I tested it locally updating `/opt/netdata/usr/share/netdata/web/main.js` and checking `/old` endpoint.
```cmd
[pc ilyam]# cat /opt/netdata/usr/share/netdata/web/main.js | grep anomaly -A 5
case 'anomaly':
if (parts.length >= 2 && parts[1].startsWith('detection')) {
chart.menu = tmp + '_detection';
}
break;
```
<details>
<summary>It works for me, see the screenshot</summary>
</details>
> fix rendering charts and menu: add anomaly_detection case

- package-lock.json
- package.json
- src/domains/charts/getChartMenu.js
- src/domains/charts/getMenu.js
- src/domains/charts/provider.js
- src/domains/dashboard/components/virtualized/provider.js
Collector updates allow us to create a more clean menu for composite charts.
- Updates are backwards compatible with old collectors.
- Single node menu remains the same, since there is no grouping by context.
> Fix prometheus menus

- package-lock.json
- src/domains/dashboard/utils/render-charts-and-menu.ts
- src/main.js
We need to remove statsd from the menu of the agent (and the cloud) dashboard, so that each application pushing statsd metrics will get its own menu item named `statsd appname`.
This PR fixes it for the agent dashboard:
Related to https://github.com/netdata/netdata/pull/12980
> remove statsd menu hint, so that statsd will have a menu item per app

- src/domains/charts/getChartMenu.js
Forgot to add the changes to the getChartMenu.js file in #395.
> fix: prefer 'k8s_cluster_name' for Kubernetes menu if exists

- src/domains/charts/getChartMenu.js
Otherwise, [K8s state](https://github.com/netdata/go.d.plugin/tree/master/modules/k8s_state#kubernetes-cluster-state-monitoring-with-netdata) got squashed into one top-level section
=>
---
@jjtsou please test
> fix: don't modify 'menu' for k8s charts on single node view

- package-lock.json
- package.json
- src/domains/chart/components/lib-charts/dygraph-chart.tsx
reuse updated shift+wheel handler from charts, for easier maintenance (logic stays the same)
https://github.com/netdata/charts/pull/108
> update wheel handler

- package-lock.json
- package.json
- src/dashboard_info.js
- src/domains/chart/chart-types.ts
- src/domains/charts/getMenuChartAttributes.js
- src/domains/dashboard/components/node-view/generate-head-charts.ts
- src/domains/dashboard/utils/netdata-dashboard.ts
related to https://github.com/netdata/netdata-cloud/issues/541
Build dashboard from dashboard_info.js, based on domain (room | node), for example:
```
"disk.util": {
room: {
info: "Info visible only in room overview",
heads: [netdataDashboard.gaugeChart("Utilization in room", "12%", "", "#FF5588")],
},
node: {
info: "Info visible only in node-view",
},
colors: "#FF5588",
heads: [netdataDashboard.gaugeChart("Utilization", "12%", "", "#FF5588")],
info: "Disk Utilization measures the amount of time the disk was busy with something. This is not related to its performance. 100% means that the system always had an outstanding operation on the disk. Keep in mind that depending on the underlying technology of the disk, 100% here may or may not be an indication of congestion.",
},
```
If `room` or …
> dashboard info by domain

- src/domains/charts/getChartMenu.js
- src/domains/dashboard/utils/render-charts-and-menu.ts
- src/main.js
There is an old problem (probably a feature at this point) with matching collector ([netdataDashboard.menu](https://github.com/netdata/dashboard/blob/master/src/dashboard_info.js#L13)) names with underscores in dashboard_info.js.
We have two collectors:
- dnsmasq
- dnsmasq_dhcp
See the example for web_log:
https://github.com/netdata/dashboard/blob/99b2edc15fab4a18b20ade408cabc725655038c0/src/main.js#L1079-L1086
This PR adds handling for dnsmasq_dhcp.
---
There are 3 files with similar logic:
1. /src/domains/dashboard/utils/render-charts-and-menu.ts
2. /src/domains/charts/getChartMenu.js
3. /src/main.js
I tested the changes using my branch + `npm run start:dashboard` and it is 3. to my understanding. 
> **Warning** I don't know if both 1. and 2. are used and how to test them.
Current …
> Handle dnsmasq_dhcp case when rendering menu

- package-lock.json
- package.json
- src/components/sidebar/space/nodes.js
Replicated nodes had wrong Off/Live badges.
> fix replicated nodes badges

- src/main.js
Our nightly builds are now hosted as releases on https://github.com/netdata/netdata-nightlies/. As such, the version check for nightly builds should be looking there instead of looking at our old GCS bucket.
> Update agent version check to reflect new hosting of nightly builds.
