netdata/dashboard

- .eslintrc.js
- dashboard-react.js
- src/App.tsx
- src/custom-dashboards-app.tsx
- src/dashboard.js
- src/dashboard_info.js
- src/domains/chart/components/chart-container.tsx
- src/domains/global/actions.ts
- src/domains/global/alarms-sagas.ts
- src/domains/global/reducer.ts
- src/domains/global/sagas.ts
- src/domains/global/selectors.ts
- src/domains/global/types.ts
- src/hooks/use-alarms.ts
- src/types/global.ts
- src/utils/name-2-id.ts
- src/utils/server-detection.test.ts
- src/utils/server-detection.ts
migrated alarms logic. It is added as a part of Dashboard.js, because sometimes static custom dashboard use those Alarms notifications (as in old app)
> Alarms refractor

- .eslintignore
- copy-assets.js
- dashboard-react.js
- src/App.tsx
- src/domains/chart/components/chart-with-loader.tsx
- src/domains/chart/components/chart.tsx
- src/domains/chart/components/disable-out-of-view.tsx
- src/domains/chart/components/lib-charts/dygraph-chart.tsx
- src/domains/chart/hooks/use-fetch-new-data-clock.ts
- src/domains/global/actions.ts
- src/domains/global/options.ts
- src/domains/global/reducer.ts
- src/domains/global/sagas.ts
- src/domains/global/selectors.ts
- src/index.tsx
- src/main.js
- src/types/global.ts
https://github.com/netdata/netdata/issues/7349
For this PR, i replaced old dashboard/main.js NETDATA.options.current state - with redux state. I hooked main.js to redux, and also built support for 4 options in main.js, related to performance:
- destroy-on-hide
- stop-updates-when-focus-is-lost
- should-eliminate-zero-dimensions
- async-on-scroll
I also hooked that state to localStorage, so after release users will have the same settings.
> 7349 performance config options

- src/App.tsx
- src/domains/chart/components/lib-charts/dygraph-chart.tsx
- src/domains/chart/components/portals.tsx
- src/domains/chart/utils/formatters.ts
- src/domains/global/actions.ts
- src/domains/global/reducer.ts
- src/index.tsx
- src/main.js
- src/store/root-reducer.ts
- src/utils/safe-equal-check.ts
hooked
- global pan and zoom
- global highlight
to main.js. That means:
- url gets updated on redux state change
- redux state is initialized based on initial url
> 7351-global-pan-zoom-mainjs

- package-lock.json
- package.json
- src/domains/chart/components/abstract-chart.tsx
- src/domains/chart/components/chart-with-loader.tsx
- src/domains/chart/components/chart.tsx
- src/domains/chart/components/lib-charts/__tests__/dygraph-chart.test.tsx
- src/domains/chart/components/lib-charts/dygraph-chart.tsx
- src/domains/chart/sagas.ts
- src/types/common.ts
- user-friendly panning into the future,
- fixed edge case when switching to global-pan-mode during live-mode api-call,
- fixed reset on double-click and double-tap.
- updated jquery & bootstrap (security reasons)
> dygraph-fixes

- package-lock.json
- package.json
- src/domains/chart/actions.ts
- src/domains/chart/components/chart-container.tsx
- src/domains/chart/components/chart.tsx
- src/domains/chart/components/disable-out-of-view.tsx
- src/domains/chart/components/portals.tsx
- src/domains/chart/reducer.ts
- src/domains/chart/sagas.ts
- src/domains/global/actions.ts
- src/domains/global/reducer.ts
- src/domains/global/selectors.ts
- src/domains/global/types.ts
- src/main.js
- src/utils/index.ts
- src/utils/utils.ts
Made necessary fixes to allow back snapshots functionalities in main.js with new Dashboard
https://github.com/netdata/netdata/issues/7766
> 7766 snapshots

- dashboard-react.js
- package-lock.json
- package.json
- src/domains/chart/actions.ts
- src/domains/chart/chart-types.ts
- src/domains/chart/components/chart-with-loader.tsx
- src/domains/chart/components/portals.tsx
- src/domains/chart/components/snapshot-loader.tsx
- src/domains/chart/reducer.ts
- src/domains/chart/sagas.ts
- src/domains/chart/selectors.ts
- src/domains/chart/utils/get-chart-url-options.ts
- src/domains/dashboard/actions.ts
- src/domains/dashboard/constants.ts
- src/domains/dashboard/reducer.ts
- src/domains/dashboard/selectors.ts
- src/domains/global/actions.ts
- src/domains/global/alarms-sagas.ts
- src/domains/global/constants.ts
- src/domains/global/sagas.ts
- src/main.js
- src/store/app-state.ts
- src/store/root-reducer.ts
- src/types/common.ts
- src/utils/netdata-sdk/index.ts
- src/utils/netdata-sdk/metrics-stream.ts
various fixes for main.js. Because of a bug i needed to switch to load snapshots via separate sagas, i fixed some dependencies for Alarms modal, and done few other small tweaks
> misc-fixes

- package-lock.json
- package.json
- src/App.test.tsx
- src/domains/chart/chart-types.ts
- src/domains/chart/components/chart-container.tsx
- src/domains/chart/components/chart-with-loader.tsx
- src/domains/chart/sagas.ts
- src/domains/chart/utils/transformDataAttributes.ts
- src/domains/dashboard/components/chart-wrapper.tsx
- src/domains/dashboard/components/head-main.tsx
- src/domains/dashboard/components/menu-sidebar.tsx
- src/domains/dashboard/components/node-view/README.md
- src/domains/dashboard/components/node-view/generate-head-charts.ts
- src/domains/dashboard/components/node-view/index.ts
- src/domains/dashboard/components/node-view/node-view.scss
- src/domains/dashboard/components/node-view/node-view.tsx
- src/domains/dashboard/components/node-view/render-single-menu.tsx
- src/domains/dashboard/components/node-view/render-submenu-name.tsx
- src/domains/dashboard/utils/netdata-dashboard.ts
- src/domains/dashboard/utils/parse-chart-string.ts
- src/domains/dashboard/utils/render-charts-and-menu.ts
- src/domains/dashboard/utils/sorting.ts
- src/index-npm.ts
- src/store/store.ts
- src/types/common.ts
- src/types/global.ts
- src/utils/date-time.test.tsx
> [master] > [nav-bars-release]

- copy-assets.js
- package.json
- src/domains/chart/components/legend-toolbox.tsx
- src/domains/chart/components/resize-handler.tsx
- src/domains/chart/utils/get-portal-node-styles.ts
- src/domains/global/sagas.ts
- fixes sign-in button when using private registry - https://github.com/netdata/dashboard/issues/32#issuecomment-594098230
- fixes initial chart height when using localStorage data from old dashboard
> sign-in button and chart height fixes

- package-lock.json
- package.json
- src/domains/chart/components/abstract-chart.tsx
- src/domains/chart/components/chart-legend.tsx
- src/domains/chart/components/chart-with-loader.tsx
- src/domains/chart/components/chart.tsx
- src/domains/chart/components/lib-charts/__tests__/dygraph-chart.test.tsx
- src/domains/chart/components/lib-charts/dygraph-chart.tsx
fix some problems when some charts have data, and others don't (global selection sync)
> dash-32-no-data-fix

- dashboard-react.js
- package-lock.json
- package.json
- public/index.html
- src/App.tsx
- src/domains/chart/components/abstract-chart.tsx
- src/domains/chart/components/lib-charts/dygraph-chart.tsx
- src/domains/chart/components/lib-charts/gauge-chart.tsx
- src/domains/chart/utils/transformDataAttributes.ts
- src/domains/dashboard/sagas.ts
- src/domains/global/actions.ts
- src/domains/global/options.ts
- src/domains/global/reducer.ts
- src/domains/global/selectors.ts
- src/index.tsx
- src/main.js
- src/store/root-reducer.ts
- src/store/root-saga.ts
- src/styles/main.css
- src/types/global.ts
- src/utils/env.ts
- src/utils/server-detection.ts
gauge & easypiechart width update
proper centering when clicking alarm in alarms-log
keep loader until react app is ready
fix top bar not showing when highlighting (few lines of code)
"check known URLs" issue
"reset" options is not hooked up
go to host node from streamed node (low priority, because that's removed on release)
> pre-release-fixes-2

- package.json
- src/domains/chart/components/chart-container.tsx
- src/domains/chart/components/chart-with-loader.tsx
- src/domains/dashboard/components/chart-wrapper.tsx
- src/domains/dashboard/components/head-main.tsx
- src/domains/dashboard/components/node-view/node-view.tsx
- src/domains/dashboard/components/node-view/render-submenu-name.tsx
Starting getting used to the code base
> NodeView fixes

- src/domains/chart/components/chart.tsx
- src/domains/chart/utils/formatters.ts
- src/domains/global/actions.ts
- src/domains/global/options.ts
- src/domains/global/reducer.ts
- src/domains/global/selectors.ts
- src/main.js
- src/types/global.ts
- src/utils/date-time.ts
- src/utils/units-conversion.ts
fixes for options:
- timezone
- temperature
- seconds_as_time
- auto-converting
> pre-release-fixes-3

- package-lock.json
- package.json
- src/domains/chart/chart-types.ts
- src/domains/chart/components/chart-with-loader.tsx
- src/domains/chart/reducer.ts
- src/domains/chart/sagas.ts
- src/domains/chart/selectors.ts
- src/domains/global/sagas.ts
- src/main.js
- src/utils/utils.ts
Cloud:
- proper node view theme
- update chart immediately after changing after/before (Cloud Table View)
Agent:
- refresh netdata after changing sync-selection option (temporary solution, to fix some edge case bugs)
- fix status text in print view modal
> multiple fixes

- package-lock.json
- package.json
- src/domains/chart/components/lib-charts/dygraph-chart.tsx
dygraph needs a special cleanup in firefox. the leak was present in old dashboard, at least there's an improvement! :)
> fix firefox memory leak

- package-lock.json
- package.json
- src/domains/global/alarms-sagas.ts
uncommited code from previous pr, i'm wondering how TS could let that pass
> fix alarms loop

- dashboard-react.js
- src/App.tsx
- src/utils/server-detection.ts
one more tweak for having netdata served under subpath
> fix loading styles from subpaths

- dashboard-react.js
- package-lock.json
- package.json
- src/domains/chart/components/legend-toolbox.tsx
- src/domains/chart/components/resize-handler.tsx
- src/domains/global/actions.ts
- src/domains/global/alarms-sagas.ts
- src/domains/global/reducer.ts
- src/main.js
- src/styles/main.css
- src/types/global.ts
fix help-tooltips styling
fix private-registry nodes deletion (cherry-pick from new-navbars release branch)
fix small sidebar "jumps" on document click (problem related probaby to bootstrap update)
> fix-tooltips-styling

- src/App.tsx
- src/components/space-panel/space-panel.tsx
- src/components/space-panel/styled.ts
- src/domains/chart/components/legend-toolbox.tsx
fixes bugs:
- Sign in button sometimes disappears after signing out.
- scrollbar in space-panel (sticky bottom part)
> pre-release-fixes-4

- package.json
- src/domains/global/sagas.ts
- src/main.js
Fixes: https://github.com/netdata/netdata/issues/8722
Fixes: https://github.com/netdata/netdata/issues/8581
> 8722 email authentication on cloud fix, SSO

- src/domains/chart/components/chart-with-loader.tsx
- relevant issue: https://github.com/netdata/product/issues/705
> optional chaining added to unsafe call.

- package-lock.json
- package.json
- src/main.js
don't wait for (document.readyState === "complete") before starting to listen to old cloud iframe (prevent some rare race condition)
> fix rare race condition in old cloud iframe

- package-lock.json
- package.json
- src/utils/netdata-sdk/metrics-stream.ts
dispatch error action also when call was terminated manually
> fix state when terminating /data call

- public/index.html
- src/App.tsx
- src/components/notifications-container/index.ts
- src/components/notifications-container/notifications-container.tsx
- src/components/notifications/index.tsx
- src/components/notifications/notifications.tsx
- src/components/notifications/styled.tsx
- src/components/ui-notification/index.ts
- src/components/ui-notification/styled.ts
- src/components/ui-notification/ui-notification.tsx
- src/domains/chart/sagas.ts
- src/domains/global/reducer.ts
- src/main.js
- src/styles/z-index.ts
- rich aclk notifications, with fixed logic to show after page load
- moved terms and conditions links to sidebar
> aclk-notifications

- package-lock.json
- package.json
- src/domains/chart/actions.ts
- src/domains/chart/reducer.ts
- src/domains/chart/sagas.ts
- src/domains/dashboard/utils/netdata-dashboard.ts
fixes:
https://github.com/netdata/product/issues/989
https://github.com/netdata/product/issues/991
https://github.com/netdata/product/issues/975
> p989-timeframe-lost-issue

- package-lock.json
- package.json
- src/domains/chart/components/chart.tsx
- src/domains/chart/utils/transformDataAttributes.ts
add an option to hide the resize handler
> custom dashboards tweaks

- package-lock.json
- package.json
- src/domains/dashboard/sagas.ts
- src/index-npm.ts
- src/main.js
- src/styles/main.css
- src/utils/hash-utils.ts
This provides a solution for sharing with cloud app the timeframe selection.
Overall there are a lot of solutions:
1) Hash params can be manipulated by the component (this is the solution provided with this PR!)
2) Cloud-app could be listening to the setGlobalChartUnderlayAction of the Dashboard component. This proved a bit more difficult than I thought. We should think about this a bit more though because we'll run into problems requiring that sooner or later!
3) Pass in a callback to the NodeView which will be called back by the Chart. This is straightforward but requires a lot of code changes to pass this callback all across the hierarchy from the NoeView to the Charts...
Let think about these. Easiest is 1 but if we find a way to solve 2 it will help us in other issues we'll be facing …
> Time selection

- public/dashboard.js
- src/utils/units-conversion.ts
ssia
Fixes: netdata/netdata#9541
> units auto-scaling: add `bytes` and `Hz`

- package-lock.json
- package.json
- src/domains/dashboard/components/node-view/node-view.scss
- src/domains/dashboard/components/node-view/node-view.tsx
- src/domains/dashboard/components/node-view/render-single-menu.tsx
- src/node-view-app.tsx
fix node-view menu update on scroll
proper "menuActive" state detection (fix "Networking Stack" & "IPv4 Networking" double active state)
fix node-view menu sidebar scrollbar position
> node-view-scroll-fix

- package-lock.json
- package.json
- src/domains/chart/components/lib-charts/dygraph-chart.tsx
- src/domains/chart/utils/transformDataAttributes.ts
- src/utils/debounce.ts
an optional feature needed by custom dashboard
> resize dygraph chart using ResizeObserver

- src/domains/chart/components/chart.tsx
fixes https://github.com/netdata/netdata/issues/8580
> fix dynamic dimension colors

- src/components/app-header/app-header.tsx
- src/domains/global/actions.ts
- src/domains/global/reducer.ts
- src/domains/global/sagas.ts
Render the app before registry access calls are success. In some cases users could have those calls pending, which was causing big lag on initial load.
fixes https://github.com/netdata/netdata/issues/9708
> non blocking registry access

- package-lock.json
- package.json
- src/domains/chart/components/chart-with-loader/chart-with-loader.tsx
This allow manually selected dimensions override Externally Selected Dimension
> Allow manually selected dimensions override externally selected dimensions

- src/utils/date-time.ts
related issue: https://github.com/netdata/netdata/issues/9371
> 9371: fix dashboard when browser is configured to have no preferred language

- src/domains/chart/components/lib-charts/dygraph-chart.tsx
- src/domains/dashboard/components/node-view/node-view.tsx
- src/domains/dashboard/components/node-view/render-single-menu.tsx
- src/domains/dashboard/utils/netdata-dashboard.ts
- src/domains/dashboard/utils/render-charts-and-menu.ts
- src/vendor/dygraph-c91c859.min.js
PR's result with menu counters:
> Menu counters for metrics correlations

- package-lock.json
- package.json
- src/domains/dashboard/components/node-view/node-view.scss
Using css variables on the :root selector, makes it easy to change/override those variables from the cloud app and provide colors based on the cloud theme.
> Used css vars for easier manipulation from external renderer.

- package-lock.json
- package.json
- public/index.html
- src/App.tsx
- src/domains/dashboard/components/sidebar-social-media-portal/index.ts
- src/domains/dashboard/components/sidebar-social-media-portal/sidebar-social-media-portal.tsx
- src/domains/dashboard/components/sidebar-social-media/index.ts
- src/domains/dashboard/components/sidebar-social-media/sidebar-social-media.tsx
- src/domains/dashboard/components/sidebar-social-media/styled.ts
- src/main.js
- src/styles/main.css
- add new social media links section below right hand sidebar
- move "Privacy policy" & "Terms and conditions" links from sidebar to the bottom of the dashboard
- leave only "Copyright 2020, Netdata, Inc" in Copyright section in the bottom of the dashboard
> social media links, terms & privacy position change

- package-lock.json
- package.json
- src/components/app-header/app-header.tsx
- src/components/app-header/components/alarms-control/alarms-control.tsx
- src/components/app-header/components/alarms-control/styled.ts
- src/components/app-header/components/node-info/styled.ts
- src/components/app-header/components/panel-control/panel-control.tsx
- src/components/app-header/components/panel-control/styled.ts
- src/components/app-header/components/version-control/styled.ts
- src/components/app-header/styled.ts
- src/components/notifications-container/notifications-container.tsx
- src/components/space-panel/components/replicated-nodes/styled.ts
- src/components/space-panel/components/space-rooms/room-label/styled.ts
- src/components/space-panel/components/space-rooms/styled.ts
- src/components/space-panel/components/visited-nodes/styled.ts
- src/components/space-panel/styled.ts
- src/components/spaces-bar/components/space-icon/styled.ts
- src/components/spaces-bar/spaces-bar.tsx
- src/components/spaces-bar/styled.tsx
- src/components/ui-notification/styled.ts
- src/domains/dashboard/components/node-view/node-view.scss
- src/domains/dashboard/components/sidebar-social-media/styled.ts
- src/global.colors.ts
- src/index-npm.ts
- src/node-view-app.tsx
- src/styles/bootstrap-3.3.7.css
- src/styles/dashboard.css
- src/theme-provider.tsx
Added style vars for default theme css files.
- Will be overridden from DashboardThemeProvider when used, otherwise fallback to default values.
> New themes

- package-lock.json
- package.json
- src/domains/chart/components/abstract-chart.tsx
- src/domains/chart/components/chart-legend-bottom.styled.ts
- src/domains/chart/components/chart-legend-bottom.tsx
- src/domains/chart/components/chart-legend-right.tsx
- src/domains/chart/components/chart-legend.tsx
- src/domains/chart/components/chart.tsx
- src/domains/chart/utils/chart-legend.test.ts
- src/domains/chart/utils/legend-utils.ts
- src/domains/chart/utils/transformDataAttributes.ts
- src/domains/dashboard/components/head-main.tsx
- src/domains/dashboard/components/menu-sidebar.tsx
- src/domains/dashboard/components/node-view/node-view.tsx
- src/domains/dashboard/components/node-view/render-submenu-name.tsx
- src/node-view-app.tsx
- src/styles/dashboard.css
- src/styles/dashboard.slate.css
https://github.com/netdata/dashboard/pull/126 needs to be merged first
> legend on bottom

- package-lock.json
- package.json
- src/domains/chart/components/chart-legend-bottom.tsx
- src/domains/chart/sagas.ts
https://github.com/netdata/product/issues/1441
> empty node-ids fix

- package-lock.json
- package.json
- src/components/app-header/app-header.tsx
- src/components/app-header/styled.ts
- src/components/space-panel/space-panel.tsx
New text for signing in cloud.
> Sign in link

- src/components/notifications/notifications.tsx
- src/components/notifications/styled.tsx
change notification which shows on cloud installation error
https://github.com/netdata/dashboard/issues/87
> cloud error installation notification

- dashboard-react.js
- package-lock.json
- package.json
- src/domains/chart/components/lib-charts/gauge-chart.tsx
- src/domains/dashboard/components/node-view/node-view.scss
- src/domains/dashboard/components/node-view/node-view.tsx
- src/domains/dashboard/components/node-view/use-update-theme.ts
- src/styles/dashboard.css
Fixed colors for charts based on [this](https://github.com/netdata/product/issues/1506) issue
> Updated charts colors based on cloud theme.

- src/components/space-panel/components/replicated-nodes/styled.ts
- src/components/space-panel/components/visited-nodes/styled.ts
- src/components/space-panel/styled.ts
- src/domains/chart/utils/chartLibrariesSettings.ts
- src/styles/dashboard.css
- src/styles/dashboard.slate.css
- fix space-panel colors in dark theme (dont change based on theme)
https://github.com/netdata/netdata/issues/10168
- keep old styles for .netdata-container-with-legend with legend-right, to not break tv.html
https://github.com/netdata/netdata/issues/10167
> space-panel dark-mode fix

- src/styles/dashboard.css
- src/styles/dashboard.slate.css
- src/styles/main.css
Fixed colors for node context description and links based on [issue](https://github.com/netdata/product/issues/1506) issue
> update node context description colors based on theme

- package-lock.json
- package.json
- src/domains/dashboard/components/menu-sidebar.tsx
- src/domains/dashboard/components/node-view/node-view.tsx
- src/domains/dashboard/components/node-view/render-single-menu.tsx
- src/domains/dashboard/components/node-view/render-submenu-name.tsx
- src/types/report.ts
Passed an optional callback to the `node-view` see we can track events.
> Created event report callback.

- package-lock.json
- package.json
- src/domains/dashboard/components/node-view/node-view.tsx
If prop defaultChart exists, then view should scroll to this chart element.
> Updated node-view to accept default chart as a prop.

- package-lock.json
- src/components/date-picker/short-pick.tsx
- src/components/date-picker/styled.ts
- src/domains/chart/components/chart-legend-bottom.styled.ts
- src/domains/global/reducer.ts
- src/styles/dashboard.css
- src/styles/dashboard.slate.css
- src/styles/main.css
- src/utils/utils.ts
- align styles for legend on bottom
- reduce dimension-items size
- fix short-pick biggest value
- set initial "after" based on screen width, just as in old dashboard
> align-legend

- src/components/date-picker/custom-picker-styles.scss
> fix datepicker bug during window resize

- package-lock.json
- package.json
- src/domains/chart/components/chart.tsx
https://github.com/netdata/netdata-cloud/issues/15
> round relative after values when clicking on toolbox zoom

- package-lock.json
- package.json
- src/domains/chart/chart-types.ts
- src/domains/chart/components/chart-legend-bottom.tsx
- src/domains/chart/components/chart-legend.tsx
- src/domains/chart/components/chart.tsx
- src/index-npm.ts
- hide resize handler when appropriate attribute is set, for legend on the bottom
- expose chartData selector and some types
> resize handler tweak and expose selector/types

- package-lock.json
- package.json
- src/domains/chart/components/chart-with-loader/chart-with-loader.tsx
https://github.com/netdata/netdata-cloud/issues/19
> Reseted the selected dimensions when group by changes.

- src/domains/chart/components/chart-with-loader/chart-with-loader.tsx
- src/styles/dashboard.css
- show spinning circles also when initial loader is present
- fix loader in node-view
> loader-fixes

- package-lock.json
- package.json
- src/components/space-panel/components/visited-nodes/styled.ts
- src/components/space-panel/components/visited-nodes/visited-nodes.tsx
- src/domains/dashboard/components/node-view/node-view.scss
- src/global.colors.ts
- src/index-npm.ts
- src/styles/dashboard.css
- src/styles/dashboard.slate.css
Change "code" colours background
https://github.com/netdata/product/issues/1633
Chart & Section headers and Right panel colour changes
https://github.com/netdata/product/issues/1600
> node-view colors

- package-lock.json
- package.json
- src/domains/chart/sagas.ts
- src/utils/fill-missing-data.ts
related to https://github.com/netdata/product/issues/1469
> fix flip when BE doesn't support the lack of this flag

- package-lock.json
- package.json
- src/domains/chart/components/lib-charts/gauge-chart.tsx
fix gauges so they show proper colours based on dimensions
before:
after:
> gauge colors fix

- package-lock.json
- package.json
- src/domains/chart/components/abstract-chart.tsx
- src/domains/chart/components/lib-charts/__tests__/dygraph-chart.test.tsx
- src/domains/chart/components/lib-charts/dygraph-chart.tsx
fix history-retention for dygraph-sparklines
> fix sparkline history retention

- package-lock.json
- package.json
- src/domains/chart/__mocks__/chart-details.ts
- src/domains/dashboard/components/node-view/node-view.tsx
- src/domains/dashboard/utils/is-kubernetes-chart.ts
- src/domains/dashboard/utils/render-charts-and-menu.ts
So we can support collections like
> Supported multiple kubernetes cluster ids.

- package-lock.json
- package.json
- src/domains/chart/actions.ts
- src/domains/chart/components/abstract-chart.tsx
- src/domains/chart/components/chart-with-loader/chart-with-loader.tsx
- src/domains/chart/components/lib-charts/group-box-chart/drawBoxes.ts
- src/domains/chart/components/lib-charts/group-box-chart/groupBox.tsx
- src/domains/chart/components/lib-charts/group-box-chart/groupBoxes.tsx
- src/domains/chart/components/lib-charts/group-box-chart/index.ts
- src/domains/chart/components/lib-charts/group-box-chart/legend.tsx
- src/domains/chart/sagas.ts
- src/domains/chart/utils/chartLibrariesSettings.ts
- src/domains/chart/utils/transformDataAttributes.ts
- src/domains/dashboard/components/node-view/node-view.tsx
- src/utils/fill-missing-data.ts
Created the `groupbox` and `groupboxes` charts to support the kubernetes feature.
[Figma Design](https://www.figma.com/file/tHcYNiK6EUmqubgk5j04Rq/Kubernetes-Dashboards-MVP0?node-id=0%3A1)
> Kubernetes heatmap

- src/App.tsx
- src/components/app-header/app-header.tsx
- src/components/space-panel/space-panel.tsx
- src/domains/global/selectors.ts
- src/utils/utils.ts
add utm-medium, utm-source to sign-in links
get the src from single source (selector)
> add utm-medium, utm-source to sign-in redirects, get the src from single source

- public/index.html
- src/domains/chart/utils/transformDataAttributes.ts
- src/domains/global/options.ts
- src/main.js
https://github.com/netdata/netdata/issues/10208
Allow users changing the legend position in settings.
> Legend bellow as setting

- package-lock.json
- package.json
- src/domains/chart/components/lib-charts/group-box-chart/groupBox.tsx
- src/domains/chart/components/lib-charts/group-box-chart/groupBoxes.tsx
- src/domains/chart/components/lib-charts/group-box-chart/kubernetes/chart.tsx
- src/domains/chart/components/lib-charts/group-box-chart/kubernetes/chartOverview.tsx
- src/domains/chart/components/lib-charts/group-box-chart/kubernetes/context.tsx
- src/domains/chart/components/lib-charts/group-box-chart/kubernetes/header.tsx
- src/domains/chart/components/lib-charts/group-box-chart/kubernetes/index.tsx
- src/domains/chart/components/lib-charts/group-box-chart/kubernetes/item.tsx
- src/domains/chart/components/lib-charts/group-box-chart/kubernetes/list.tsx
- src/domains/chart/components/lib-charts/group-box-chart/kubernetes/metrics.tsx
- src/domains/chart/components/lib-charts/group-box-chart/kubernetes/popover.tsx
- src/domains/chart/components/lib-charts/group-box-chart/kubernetes/section.tsx
- src/domains/chart/components/lib-charts/group-box-chart/kubernetes/tabs.tsx
- src/domains/chart/components/lib-charts/group-box-chart/legend.tsx
* Make node clickable
* Added testids
* UX improvements
> Kubernetes data testid

- public/index.html
- src/domains/global/alarms-sagas.ts
- src/domains/global/sagas.ts
- src/main.js
- src/styles/main.css
- src/types/global.ts
remove unused main.js/index.html code (mostly related to the old cloud)
> main-js cleaning

- package-lock.json
- package.json
- src/domains/chart/components/lib-charts/dygraph-chart.tsx
- src/domains/chart/components/lib-charts/sparkline-chart.tsx
- src/domains/chart/hooks/use-proceeded-chart.ts
- src/domains/chart/sagas.ts
- src/styles/dashboard.css
General fixies around the chart styling and functionality.
> Charts fixes

- src/domains/global/sagas.ts
https://github.com/netdata/dashboard/issues/238
> link person id to posthog

- src/components/space-panel/components/replicated-nodes/styled.ts
> allow multirow names in replicated-nodes list

- src/domains/dashboard/components/node-view/node-view.scss
Set width of right-side menu similarly to dashboard
> cloud-right-sidebar-width-fix

- public/goto-host-from-alarm.html
- src/domains/global/sagas.ts
- src/domains/global/utils.ts
- Change several posthog bindings
- remove GTM and enable posthog without feature-flag
- add separate bindings for demo servers
fixes https://github.com/netdata/dashboard/issues/240,
https://github.com/netdata/dashboard/issues/241
https://github.com/netdata/dashboard/issues/244
https://github.com/netdata/dashboard/issues/245
https://github.com/netdata/dashboard/issues/246
https://github.com/netdata/dashboard/issues/248
> mask referrer in posthog

- public/dashboard.js
- public/demosites.html
- src/domains/chart/components/lib-charts/proceeded-chart-disclaimer.tsx
Replace legacy docs.netdata.cloud links with currently live ones
> Update links: change docs.netdata.cloud to learn.netdata.cloud

- package-lock.json
- package.json
- src/domains/charts/chartHead/chartHead.js
- src/domains/charts/charts/charts.js
- src/domains/charts/charts/context.js
- src/domains/charts/charts/useEstimatedHeight.js
- src/domains/charts/getChartHeads.js
- src/domains/charts/provider.js
The chart attributes should be provided by the client.
> Remove attributes provider

- .devcontainer/devcontainer.json
With the existence of the `.devcontainer` directory, when a user opens the repository using VS Code, they will be automatically prompted to re-open the directory from inside the developer container. T
The VS Code window is connected to that container, being able to both use extensions to facilitate programming, tools. to check that the code is according to our standards (e.g flake8) and use VS Code sidebar as a GUI for file navigation inside the container. Finally, VS Code syncs the directory that we just opened inside the container, meaning that any file we place from our host machine into that directory (e.g netdata), it will be synced inside the container. 
The developer container contains all the required dependencies to build from source:
- netdata
- python.d.plugin
- go.d.plugin
- …
> Support VS Code container devenv

- package-lock.json
- package.json
- src/domains/charts/charts/context.js
- src/domains/charts/index.js
- src/domains/dashboard/components/virtualized/useMakeList.js
Added go to chart functionality.
> Refactor custom dashboard

- package-lock.json
- package.json
- src/components/header/index.js
- src/components/header/news/dataSource/index.js
- src/components/header/news/index.js
- src/components/news/container.js
- src/components/news/header.js
- src/components/news/index.js
- src/components/news/item/anchor.js
- src/components/news/item/image.js
- src/components/news/item/index.js
**Designs**:
https://www.figma.com/file/RgebwHKHvTCAlTmIxLsb6l/New-Cloud-and-Agent-navigation-%231629?node-id=535%3A935
**Unseen**:
**Seen**:
> Agent news and features

- public/goto-host-from-alarm.html
Propagate new alarm hash params in goto-host-from-alarm.html file (for private registry)
> goto-host-from-alarm.html new hash params

- package-lock.json
- package.json
- src/dashboard_info.js
- update dashboard_info.js (to match the one from the Agent)
- add disk_space percentage gauges to `heads` sections
> Update dashboard info

- src/components/app-header/components/version-control/index.ts
- src/components/app-header/components/versionControl/index.js
- src/components/header/globalControls/playOptions/index.js
- src/components/header/globalControls/playPausePill/index.js
- src/components/header/news/index.js
- src/components/header/options/index.js
- src/components/header/version.js
- src/components/tooltips/customTooltip.js
- src/components/tooltips/getContent.js
- src/components/tooltips/index.js
- src/index-npm.ts
Fixes [this](https://app.zenhub.com/workspaces/product-5ea1534e9ff5df7daace00d5/issues/netdata/product/2305)
> Added topbar tooltips.

- src/domains/charts/getChartMenu.js
- src/domains/dashboard/utils/render-charts-and-menu.ts
- src/main.js
Needed for https://github.com/vkalintiris/netdata/pull/8
> rendering charts and menu: add anomaly_detection case

- package-lock.json
- package.json
- src/dashboard_info.js
updated dashboard_info.js so https://github.com/netdata/dashboard/pull/314 can be used in cloud
> Anomalies section

- src/components/header/options/index.js
- src/main.js
fix exporting snapshots when default relative `after` is changed (use`defaultAfter` instead of specified initially options.duretion)
> different approach for export-snapshot problem

- src/components/header/options/index.js
https://github.com/netdata/dashboard/issues/328
> setGlobalPauseAction on export modal open

- package-lock.json
- package.json
- src/domains/charts/chartMenuGroup/title.js
- src/domains/charts/chartSubMenu/title.js
- src/domains/charts/description/index.js
This PR implements updates needed for issue [#2215](https://github.com/netdata/product/issues/2215)
* Remove icon from page heading
* Change HTML tag of page sub-headings
* Update color of page heading, page sub-heading and description
* Add scripts to update `cloud-frontend` on development mode
> Fix heading and description styles

- src/components/notifications/notifications.tsx
- src/components/notifications/styled.tsx
- src/components/ui-notification/styled.ts
fix error notification on dark theme
> Fix error notifications

- package-lock.json
- package.json
- src/main.js
https://github.com/netdata/dashboard/issues/346
> set initial after and before from hashParams

- package-lock.json
- package.json
- src/components/header/index.js
- src/components/header/protoBuf/dropdown.js
- src/components/header/protoBuf/index.js
- src/domains/global/selectors.ts
Add notification in header when node is not prepared for protobuf (new arch)
2 things will change before merge:
- due date (when we'll stop supporting nodes without proto-buf)
- link to docs
> Protobuf support notification

- src/domains/charts/getChartMenu.js
Fixes [#2896](https://github.com/netdata/cloud-frontend/issues/2896)
> Moved disk inodes and space under mount points.

- package-lock.json
- package.json
This issue resolves issue [#2888](https://github.com/netdata/product/issues/2888)
Update version of `@netdata/netdata-ui` package, that includes the update of "Need Help?" section
> chore: update need help section

- src/components/header/logo/index.js
- src/components/sidebar/netdataLogo.js
This PR resolves issue [#3126](https://github.com/netdata/cloud-frontend/issues/3126) for `Agent`
Update color of NetData's logo
> chore: update color of netdata's logo on left sidebar

- package-lock.json
- package.json
This PR resolves [this comment](https://github.com/netdata/netdata/pull/12585#issuecomment-1086023723)
Includes the updated links of new GitHub issues
> chore: update version of netdata-ui

- package-lock.json
- package.json
- src/components/sidebar/spaces/index.js
This PR resolves issue [Cloud Frontend #3126](https://github.com/netdata/cloud-frontend/issues/3126) for **Agent**
Update NetData logo on left sidebar with latest
> chore: update logo on left sidebar

- package-lock.json
- package.json
- src/domains/charts/menuGroup/menuGroup.js
- src/domains/charts/subMenu/menuItem.js
- src/domains/dashboard/components/node-view/node-view.scss
- src/styles/main.css
**Before**
**After**
Fixes: https://github.com/netdata/cloud-frontend/issues/3049
cc: @burbuli8ra @novykh I haven't reviewed the changes on the Agent, if you can please review them.
> Reduce spacing of menu items in right bar

- src/domains/dashboard/components/virtualized/provider.js
Reduce left/right paddings of main view to 16px from 24px
Dependency to https://github.com/netdata/cloud-frontend/pull/3219
Fixes: https://github.com/netdata/cloud-frontend/issues/3208
> Update main view paddings

- src/components/header/ACLK/cloud-connection-status-modal.tsx
- src/components/sidebar/spaces/userSettings.js
- src/domains/dashboard/components/migration-manager/migration-manager.tsx
- src/domains/dashboard/components/migration-modal/migration-modal.js
- src/domains/dashboard/components/migration-modal/use-migration-modal.tsx
Needed for [#2914](https://github.com/netdata/product/issues/2914)
> Updated redirection to cloud in the same window.

- src/domains/dashboard/components/virtualized/provider.js
Resets top padding in order to fix scroll position and reset empty space on top
Dependency: https://github.com/netdata/cloud-frontend/pull/3372
> Update overview container top padding

- src/components/sidebar/space/index.js
- src/components/sidebar/space/visitedNodes/index.js
- src/components/sidebar/space/visitedNodes/styled.js
fixes https://github.com/netdata/netdata/issues/13094
> bring back visited nodes for private registry

- .github/workflows/add-bugs.yml
Based on the following the work done on netdata/product to try to put a workflow to automate the moving of new bugs into the Product Bugs project ([this PR on product](https://github.com/netdata/product/pull/2962))
> workflow to add bugs to project board

- package-lock.json
- package.json
This PR is related to issue [Cloud FE #3625](https://github.com/netdata/cloud-frontend/issues/3625)
Update version of `@netdata/netdata-ui` package
> chore: update version of @netdata/netdata-ui

- src/dashboard_info.js
Manual sync with https://github.com/netdata/netdata/blob/master/web/gui/dashboard_info.js
I did no tests (rendering infos on the Cloud), but this is a copy of the dashboard_info.sh file from the netdata repo. Should be no problems.
> chore: update dashboard_info.js

- src/domains/chart/components/lib-charts/dygraph-chart.tsx
Fix a bug, that fortunately didn't made it into release yet.
> fix scroll direction

- package-lock.json
- package.json
- src/components/date-picker/reduxDatePickerContainer.js
- src/main.js
Propagate timerange to print view, both for absolute and relative after/before params
https://github.com/netdata/dashboard/issues/371
> print-mode time window fix
